version: '3.5'
services:
  frontend:
    container_name: front_container
    image: sergeiokhlopkov/frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      REACT_APP_URL_TO_SERVER: "http://localhost:8080/Integral/calculate"

  backend:
    container_name: back_container
    hostname: backend
    image: sergeiokhlopkov/backend
    ports:
      - 8080:8089
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8089"
